## Setup a local cluster using kind
## We need to mount to extra path from the host
## 1. /proc - To expose information of the running processes on host
## 2. /usr/src - To expose kernel headers allowing dynamic ebpf programs to be compiled
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kepler-demo-local-cluster
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3@sha256:3966ac761ae0136263ffdb6cfd4db23ef8a83cba8a463690e98317add2c9ba72
    extraMounts:
    - hostPath: /proc
      containerPath: /proc-host
    - hostPath: /usr/src
      containerPath: /usr/src
